uses: WTFender/wpscan-action@v1.0
with:
  url: 'http://3.87.1.30/'


  on:
  push:
    branches: [ main ]
jobs:
  wpscan:
    runs-on: ubuntu-latest
    steps:
      - name: WPScan
        uses: WTFender/wpscan-action@v1.0
        id: wpscan
        with:
          url: 'http://3.87.1.30/'
          token: ${{ secrets.WPSCAN_TOKEN }}
          
      - name: Scan Results
        run: |
          echo ${{ steps.wpscan.outputs.resultb64 }}
          echo ${{ steps.wpscan.outputs.result }}
