name: REMOVE IP

on:

  push:
    branches:  
      [main]   
jobs:
  Remove-IP:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
      run: |
        aws ec2 describe-instances

