name: REMOVE IP

on:

  push:
    branches:  
      [main]   
jobs:
  Remove-IP:
    runs-on: ubuntu-latest
    steps:
    - name: Remove IP
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
      run: aws ec2 revoke-security-group-ingress \
          --group-id sg-04d9ca0541efd2157 \
          --ip-permissions "[ \
                              { \
                              \"IpProtocol\": \"tcp\", \
                              \"FromPort\": 22, \
                              \"ToPort\": 22, \
                              \"IpRanges\": [ \
                                              { \
                                              \"CidrIp\": \"138.36.230.92/32\" \
                                              } \
                                            ] \
                              } \
                            ]" 
                            
