name: ceps workflow

on: 
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: deploy teste cep
        uses:   actions/checkout@v3
      
      - name: Dependencies install
        run: npm install