name: REMOVE IP

on:

  push:
    branches:  
      [main]   
jobs:
  Remove-IP:
    runs-on: ubuntu-latest
    steps:
    - name: Remove IP
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
      run: aws ec2 revoke-security-group-ingress --group-name launch-wizard-3  --protocol tcp --port 22   --cidr 138.36.230.92/32
