name: ceps workflow

on: 
  push:
    branches:
      - main
env:
  NODE_VERSION: 14.x
      
jobs:
  test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: deploy teste cep
        uses:   actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
 
      