name: REMOVE IP

on:

  push:
    branches:  
      [main]   
jobs:
  Remove-IP:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: personal
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: us-east-2
          role-session-name: remove-ip
    
