name: ceps workflow

on: 
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: deploy teste cep
        uses:   actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
            node-version: 10.24.1

      - name: Dependencies install
        run: npm install