name: ceps workflow

on: 
  push:
    branches:
      - main
      

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: ./
      - run: npm t
        working-directory: ./
