name: ceps workflow

on: 
  push:
    branches:
      - main

jobs: 
  ecr:
    runs-on: ubuntu-latest
    environment: ecr-lab
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: ${{ secrets.AWS_REGION }}
      
