name: ceps workflow

on: 
  push:
    branches:
      - main
      

jobs: 
  ecr:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    environment: personal

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::459826126373:role/ecr-test
          aws-region: us-east-1
          role-session-name: ecr-test
      
    